language: scala
scala:
  - "2.11.6" 
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
env:
  - GUAVA_VERSION=15.0
  - GUAVA_VERSION=16.0
  - GUAVA_VERSION=16.0.1
  - GUAVA_VERSION=17.0
  - GUAVA_VERSION=18.0
